// <auto-generated />
using System;
using DataAccess.DataBaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations.ReportingDB
{
    [DbContext(typeof(ReportingDBContext))]
    [Migration("20241019142132_SeedReportingData")]
    partial class SeedReportingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DataAccess.DataModels.ReportingDataModel", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("reports");

                    b.HasData(
                        new
                        {
                            UUID = "ad4f03d1-8c30-4bfe-a291-4fee104d6317",
                            ReportDescription = "Sample report description 1",
                            ReportState = "Pending",
                            RequestedDate = new DateTime(2024, 10, 17, 17, 21, 32, 353, DateTimeKind.Local).AddTicks(3083)
                        },
                        new
                        {
                            UUID = "94ec435b-c0d5-4644-a0f5-96658500a03b",
                            ReportDescription = "Sample report description 2",
                            ReportState = "Processing",
                            RequestedDate = new DateTime(2024, 10, 18, 17, 21, 32, 353, DateTimeKind.Local).AddTicks(3107)
                        },
                        new
                        {
                            UUID = "bd5a68bd-2c0d-4ac6-a058-5ecf54b28824",
                            ReportDescription = "Sample report description 3",
                            ReportState = "Shipped",
                            RequestedDate = new DateTime(2024, 10, 19, 17, 21, 32, 353, DateTimeKind.Local).AddTicks(3108)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
