// <auto-generated />
using System;
using DataAccess.DataBaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations.ReportingDB
{
    [DbContext(typeof(ReportingDBContext))]
    partial class ReportingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DataAccess.DataModels.ReportingServiceModels.ReportingDataModel", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("ReportState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("reports");
                });
#pragma warning restore 612, 618
        }
    }
}
